// Generated by FlutterFever JSON to Dart Tool
// Root model: RegisterModel

class RegisterModel {
  final bool success;
  final String message;
  final RegisterModelData? data;

  RegisterModel({
    required this.success,
    required this.message,
    required this.data,
  });

  RegisterModel copyWith({
    bool? success,
    String? message,
    RegisterModelData? data,
  }) {
    return RegisterModel(
      success: success ?? this.success,
      message: message ?? this.message,
      data: data ?? this.data,
    );
  }

  factory RegisterModel.fromMap(Map<String, dynamic> json) {
    return RegisterModel(
      success: json['success'],
      message: json['message'],
      data: json['data'] != null
          ? RegisterModelData.fromMap(Map<String, dynamic>.from(json['data']))
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {'success': success, 'message': message, 'data': data?.toMap()};
  }
}

class RegisterModelData {
  final String jwt;
  final RegisterModelDataUser? user;

  RegisterModelData({required this.jwt, this.user});

  RegisterModelData copyWith({String? jwt, RegisterModelDataUser? user}) {
    return RegisterModelData(jwt: jwt ?? this.jwt, user: user ?? this.user);
  }

  factory RegisterModelData.fromMap(Map<String, dynamic> json) {
    return RegisterModelData(
      jwt: json['jwt'],
      user: json['user'] != null
          ? RegisterModelDataUser.fromMap(
              Map<String, dynamic>.from(json['user']),
            )
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {'jwt': jwt, 'user': user?.toMap()};
  }
}

class RegisterModelDataUser {
  final int id;
  final String username;
  final String email;
  final String provider;
  final int confirmed;
  final int blocked;
  final DateTime? createdat;
  final DateTime? updatedat;
  final DateTime? publishedat;

  RegisterModelDataUser({
    required this.id,
    required this.username,
    required this.email,
    required this.provider,
    required this.confirmed,
    required this.blocked,
    this.createdat,
    this.updatedat,
    this.publishedat,
  });

  RegisterModelDataUser copyWith({
    int? id,
    String? username,
    String? email,
    String? provider,
    int? confirmed,
    int? blocked,
    DateTime? createdat,
    DateTime? updatedat,
    DateTime? publishedat,
  }) {
    return RegisterModelDataUser(
      id: id ?? this.id,
      username: username ?? this.username,
      email: email ?? this.email,
      provider: provider ?? this.provider,
      confirmed: confirmed ?? this.confirmed,
      blocked: blocked ?? this.blocked,
      createdat: createdat ?? this.createdat,
      updatedat: updatedat ?? this.updatedat,
      publishedat: publishedat ?? this.publishedat,
    );
  }

  factory RegisterModelDataUser.fromMap(Map<String, dynamic> json) {
    return RegisterModelDataUser(
      id: json['id'],
      username: json['username'],
      email: json['email'],
      provider: json['provider'],
      confirmed: json['confirmed'],
      blocked: json['blocked'],
      createdat: json['createdAt'] != null
          ? DateTime.parse(json['createdAt'])
          : null,
      updatedat: json['updatedAt'] != null
          ? DateTime.parse(json['updatedAt'])
          : null,
      publishedat: json['publishedAt'] != null
          ? DateTime.parse(json['publishedAt'])
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'username': username,
      'email': email,
      'provider': provider,
      'confirmed': confirmed,
      'blocked': blocked,
      'createdAt': createdat?.toIso8601String(),
      'updatedAt': updatedat?.toIso8601String(),
      'publishedAt': publishedat?.toIso8601String(),
    };
  }
}
