// Generated by FlutterFever JSON to Dart Tool
// Root model: Productmodel

class Productmodel {
  final int id;
  final String idCategory;
  final String categoryName;
  final String documentid;
  final String name;
  final String description;
  final bool available;
  final int stock;
  final dynamic expired;
  final DateTime? createdat;
  final DateTime? updatedat;
  final DateTime? publishedat;

  Productmodel({
    required this.id,
    required this.idCategory,
    required this.categoryName,
    required this.documentid,
    required this.name,
    required this.description,
    required this.available,
    required this.stock,
    this.expired,
    this.createdat,
    this.updatedat,
    this.publishedat,
  });

  Productmodel copyWith({
    int? id,
    String? idCategory,
    String? categoryName,
    String? documentid,
    String? name,
    String? description,
    bool? available,
    int? stock,
    dynamic expired,
    DateTime? createdat,
    DateTime? updatedat,
    DateTime? publishedat,
  }) {
    return Productmodel(
      id: id ?? this.id,
      idCategory: idCategory ?? this.idCategory,
      categoryName: categoryName ?? this.categoryName,
      documentid: documentid ?? this.documentid,
      name: name ?? this.name,
      description: description ?? this.description,
      available: available ?? this.available,
      stock: stock ?? this.stock,
      expired: expired ?? this.expired,
      createdat: createdat ?? this.createdat,
      updatedat: updatedat ?? this.updatedat,
      publishedat: publishedat ?? this.publishedat,
    );
  }

  factory Productmodel.fromMap(Map<String, dynamic> json) {
    return Productmodel(
      id: json['id'],
      idCategory: json['id_category'],
      categoryName: json['category_name'],
      documentid: json['documentId'],
      name: json['name'],
      description: json['description'],
      available: json['available'],
      stock: json['stock'],
      expired: json['expired'],
      createdat: json['createdAt'] != null
          ? DateTime.parse(json['createdAt'])
          : null,
      updatedat: json['updatedAt'] != null
          ? DateTime.parse(json['updatedAt'])
          : null,
      publishedat: json['publishedAt'] != null
          ? DateTime.parse(json['publishedAt'])
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'id_category': idCategory,
      'category_name': categoryName,
      'documentId': documentid,
      'name': name,
      'description': description,
      'available': available,
      'stock': stock,
      'expired': expired,
      'createdAt': createdat?.toIso8601String(),
      'updatedAt': updatedat?.toIso8601String(),
      'publishedAt': publishedat?.toIso8601String(),
    };
  }
}
