// Generated by FlutterFever JSON to Dart Tool
// Root model: ProductDeleteModel

class ProductDeleteModel {
  final String message;

  ProductDeleteModel({required this.message});

  ProductDeleteModel copyWith({String? message}) {
    return ProductDeleteModel(message: message ?? this.message);
  }

  factory ProductDeleteModel.fromMap(Map<String, dynamic> json) {
    return ProductDeleteModel(message: json['message']);
  }

  Map<String, dynamic> toMap() {
    return {'message': message};
  }
}
