// Generated by FlutterFever JSON to Dart Tool
// Root model: ProductDetailModel

import 'package:flutter_counter_bloc/products/models/product_meta.dart';

class ProductDetailModel {
  final ProductdetailmodelData? data;
  final ProductMetaModel? meta;

  ProductDetailModel({
    this.data,
    this.meta,
  });

  ProductDetailModel copyWith({
    ProductdetailmodelData? data,
    ProductMetaModel? meta,
  }) {
    return ProductDetailModel(
      data: data ?? this.data,
      meta: meta ?? this.meta,
    );
  }

  factory ProductDetailModel.fromMap(Map<String, dynamic> json) {
    return ProductDetailModel(
      data: json['data'] != null ? ProductdetailmodelData.fromMap(Map<String, dynamic>.from(json['data'])) : null,
      meta: json['meta'] != null ? ProductMetaModel.fromMap(Map<String, dynamic>.from(json['meta'])) : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'data': data?.toMap(),
      'meta': meta?.toMap(),
    };
  }
}

class ProductdetailmodelData {
  final int id;
  final String documentid;
  final bool available;
  final int stock;
  final dynamic expired;
  final DateTime? createdat;
  final DateTime? updatedat;
  final DateTime? publishedat;
  final String description;
  final String name;

  ProductdetailmodelData({
    required this.id,
    required this.documentid,
    required this.available,
    required this.stock,
    this.expired,
    this.createdat,
    this.updatedat,
    this.publishedat,
    required this.description,
    required this.name,
  });

  ProductdetailmodelData copyWith({
    int? id,
    String? documentid,
    bool? available,
    int? stock,
    dynamic expired,
    DateTime? createdat,
    DateTime? updatedat,
    DateTime? publishedat,
    String? description,
    String? name,
  }) {
    return ProductdetailmodelData(
      id: id ?? this.id,
      documentid: documentid ?? this.documentid,
      available: available ?? this.available,
      stock: stock ?? this.stock,
      expired: expired ?? this.expired,
      createdat: createdat ?? this.createdat,
      updatedat: updatedat ?? this.updatedat,
      publishedat: publishedat ?? this.publishedat,
      description: description ?? this.description,
      name: name ?? this.name,
    );
  }

  factory ProductdetailmodelData.fromMap(Map<String, dynamic> json) {
    return ProductdetailmodelData(
      id: json['id'],
      documentid: json['documentId'],
      available: json['available'],
      stock: json['stock'],
      expired: json['expired'],
      createdat: json['createdAt'] != null ? DateTime.parse(json['createdAt']) : null,
      updatedat: json['updatedAt'] != null ? DateTime.parse(json['updatedAt']) : null,
      publishedat: json['publishedAt'] != null ? DateTime.parse(json['publishedAt']) : null,
      description: json['description'],
      name: json['name'],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'documentId': documentid,
      'available': available,
      'stock': stock,
      'expired': expired,
      'createdAt': createdat?.toIso8601String(),
      'updatedAt': updatedat?.toIso8601String(),
      'publishedAt': publishedat?.toIso8601String(),
      'description': description,
      'name': name,
    };
  }
}

