// Generated by FlutterFever JSON to Dart Tool

import 'package:flutter_counter_bloc/login/models/user_model.dart';

// Generated by FlutterFever JSON to Dart Tool
// Root model: LoginModel

class LoginModel {
  final bool success;
  final String message;
  final LoginModelData? data;

  LoginModel({required this.success, required this.message, this.data});

  LoginModel copyWith({bool? success, String? message, LoginModelData? data}) {
    return LoginModel(
      success: success ?? this.success,
      message: message ?? this.message,
      data: data ?? this.data,
    );
  }

  factory LoginModel.fromMap(Map<String, dynamic> json) {
    return LoginModel(
      success: json['success'],
      message: json['message'],
      data: json['data'] != null
          ? LoginModelData.fromMap(Map<String, dynamic>.from(json['data']))
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {'success': success, 'message': message, 'data': data?.toMap()};
  }
}

class LoginModelData {
  final String jwt;
  final LoginModelDataUser? user;

  LoginModelData({required this.jwt, this.user});

  LoginModelData copyWith({String? jwt, LoginModelDataUser? user}) {
    return LoginModelData(jwt: jwt ?? this.jwt, user: user ?? this.user);
  }

  factory LoginModelData.fromMap(Map<String, dynamic> json) {
    return LoginModelData(
      jwt: json['jwt'],
      user: json['user'] != null
          ? LoginModelDataUser.fromMap(Map<String, dynamic>.from(json['user']))
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {'jwt': jwt, 'user': user?.toMap()};
  }
}

class LoginModelDataUser {
  final int id;
  final String username;
  final String email;
  final String provider;
  final int confirmed;
  final int blocked;
  final DateTime? createdat;
  final DateTime? updatedat;
  final DateTime? publishedat;
  final String password;

  LoginModelDataUser({
    required this.id,
    required this.username,
    required this.email,
    required this.provider,
    required this.confirmed,
    required this.blocked,
    this.createdat,
    this.updatedat,
    this.publishedat,
    required this.password,
  });

  LoginModelDataUser copyWith({
    int? id,
    String? username,
    String? email,
    String? provider,
    int? confirmed,
    int? blocked,
    DateTime? createdat,
    DateTime? updatedat,
    DateTime? publishedat,
    String? password,
  }) {
    return LoginModelDataUser(
      id: id ?? this.id,
      username: username ?? this.username,
      email: email ?? this.email,
      provider: provider ?? this.provider,
      confirmed: confirmed ?? this.confirmed,
      blocked: blocked ?? this.blocked,
      createdat: createdat ?? this.createdat,
      updatedat: updatedat ?? this.updatedat,
      publishedat: publishedat ?? this.publishedat,
      password: password ?? this.password,
    );
  }

  factory LoginModelDataUser.fromMap(Map<String, dynamic> json) {
    return LoginModelDataUser(
      id: json['id'],
      username: json['username'],
      email: json['email'],
      provider: json['provider'],
      confirmed: json['confirmed'],
      blocked: json['blocked'],
      createdat: json['createdAt'] != null
          ? DateTime.parse(json['createdAt'])
          : null,
      updatedat: json['updatedAt'] != null
          ? DateTime.parse(json['updatedAt'])
          : null,
      publishedat: json['publishedAt'] != null
          ? DateTime.parse(json['publishedAt'])
          : null,
      password: json['password'],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'username': username,
      'email': email,
      'provider': provider,
      'confirmed': confirmed,
      'blocked': blocked,
      'createdAt': createdat?.toIso8601String(),
      'updatedAt': updatedat?.toIso8601String(),
      'publishedAt': publishedat?.toIso8601String(),
      'password': password,
    };
  }
}
