// Generated by FlutterFever JSON to Dart Tool

import 'package:flutter_counter_bloc/login/models/user_model.dart';

class LoginModel {
  final String jwt;
  final UserModel? user;

  LoginModel({required this.jwt, this.user});

  LoginModel copyWith({String? jwt, UserModel? user}) {
    return LoginModel(jwt: jwt ?? this.jwt, user: user ?? this.user);
  }

  factory LoginModel.fromMap(Map<String, dynamic> json) {
    return LoginModel(
      jwt: json['jwt'],
      user: json['user'] != null
          ? UserModel.fromMap(Map<String, dynamic>.from(json['user']))
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {'jwt': jwt, 'user': user?.toMap()};
  }
}
